# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/vivado-risc-v/board/arty-a7-100t/top.xdc

# XDC: imports/vivado-risc-v/board/arty-a7-100t/sdc.xdc

# XDC: imports/vivado-risc-v/board/arty-a7-100t/uart.xdc

# XDC: imports/vivado-risc-v/board/arty-a7-100t/ethernet.xdc

# TCL: imports/vivado-risc-v/ethernet/verilog-ethernet/lib/axis/syn/vivado/sync_reset.tcl

# TCL: imports/vivado-risc-v/ethernet/verilog-ethernet/lib/axis/syn/vivado/axis_async_fifo.tcl

# TCL: imports/vivado-risc-v/ethernet/verilog-ethernet/syn/vivado/eth_mac_fifo.tcl

# TCL: imports/vivado-risc-v/board/timing-constraints.tcl

# XDC: imports/arty-a7-100t/gpio.xdc

# XDC: new/xadc.xdc

# Block Designs: bd/riscv/riscv.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv || ORIG_REF_NAME==riscv} -quiet] -quiet

# IP: bd/riscv/ip/riscv_axi_smc_1_0/riscv_axi_smc_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_axi_smc_1_0 || ORIG_REF_NAME==riscv_axi_smc_1_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_mem_reset_control_0_0/riscv_mem_reset_control_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_mem_reset_control_0_0 || ORIG_REF_NAME==riscv_mem_reset_control_0_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_mig_7series_0_0/riscv_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_mig_7series_0_0 || ORIG_REF_NAME==riscv_mig_7series_0_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_Ethernet_0/riscv_Ethernet_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_Ethernet_0 || ORIG_REF_NAME==riscv_Ethernet_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_SD_0/riscv_SD_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_SD_0 || ORIG_REF_NAME==riscv_SD_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_UART_0/riscv_UART_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_UART_0 || ORIG_REF_NAME==riscv_UART_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_XADC_0/riscv_XADC_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_XADC_0 || ORIG_REF_NAME==riscv_XADC_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_ethernet_stream_0_0/riscv_ethernet_stream_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_ethernet_stream_0_0 || ORIG_REF_NAME==riscv_ethernet_stream_0_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_io_axi_m_0/riscv_io_axi_m_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_io_axi_m_0 || ORIG_REF_NAME==riscv_io_axi_m_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_io_axi_s_0/riscv_io_axi_s_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_io_axi_s_0 || ORIG_REF_NAME==riscv_io_axi_s_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_xlconcat_0_0/riscv_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_xlconcat_0_0 || ORIG_REF_NAME==riscv_xlconcat_0_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_xlconstant_0_0/riscv_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_xlconstant_0_0 || ORIG_REF_NAME==riscv_xlconstant_0_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_axi_gpio_0_0/riscv_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_axi_gpio_0_0 || ORIG_REF_NAME==riscv_axi_gpio_0_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_axi_timer_0_1/riscv_axi_timer_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_axi_timer_0_1 || ORIG_REF_NAME==riscv_axi_timer_0_1} -quiet] -quiet

# IP: bd/riscv/ip/riscv_clk_wiz_0_0/riscv_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_clk_wiz_0_0 || ORIG_REF_NAME==riscv_clk_wiz_0_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_util_vector_logic_0_0/riscv_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_util_vector_logic_0_0 || ORIG_REF_NAME==riscv_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/riscv/ip/riscv_RocketChip_0/riscv_RocketChip_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_RocketChip_0 || ORIG_REF_NAME==riscv_RocketChip_0} -quiet] -quiet

# XDC: /home/alis/gpio/vivado-risc-v/workspace/rocket64b1/vivado-arty-a7-100t-riscv/arty-a7-100t-riscv.gen/sources_1/bd/riscv/riscv_ooc.xdc
